version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: spendingplan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@yahoo.com
      PGADMIN_DEFAULT_PASSWORD: pass123
    ports:
      - "82:80"
    depends_on:
      - postgres

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: