spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: spendingplan
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate.ddl-auto: update
        show-sql: true
    security:
        token:
            secret: 123456
    cache:
        type: redis
        host: localhost
        port: 6379
        redis:
            timeout: 2000
            lettuce:
                pool:
                    max-wait: 2000
                client-options:
                    auto-reconnect: false
jwt:
    key: SVpwfvAu5fpGg6ICHoiMOXlWwIg0uJGSOcmiGxXOriu58QbrQMBoRTAB5Rom5gjR
    access-token-expiration: 3600000
    refresh-token-expiration: 86400000