spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: spendingplan
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate.ddl-auto: update
        show-sql: true
api:
    security:
        token:
            secret: 123456

jwt:
    key: SVpwfvAu5fpGg6ICHoiMOXlWwIg0uJGSOcmiGxXOriu58QbrQMBoRTAB5Rom5gjR
    access-token-expiration: 3600000
    refresh-token-expiration: 86400000

cache:
    type: redis

redis:
    host: localhost
    port: 6379
    timeout: 2000
